# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: naveen321ca@gmail.com
author_name: naveencagit321
cloud_provider: none
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: project_4

